import Head from 'next/head'
import React from 'react'

function Heads() {
  return (
    <>
    <Head>
        <title> Daily News Actual </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://flowbite.com/docs/images/logo.svg" />
      </Head>{" "}
    </>
  )
}

export default Heads;