import Head from "next/head";
import Nav from "../Components/nav";
import Newsgrid from "../Components/newsgrid";
import Newscat from "../Components/newscategory";
// import Card from "../Components/card";
// import Hero from "../Components/hero";
// import Blogsection from "../Components/blogsection";
// import Bloglink from "../Components/bloglink";
import Footer from "@/Components/footer";

export default function Category() {
    return (
      <>
        <Head>
          <title> Daily News Actual </title>{" "}
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="https://flowbite.com/docs/images/logo.svg" />
        </Head>{" "}
        <Nav />
        <Newsgrid/>
        <Newscat/>
        {/* <Hero />
        <Card />
        <Blogsection />
        <Bloglink /> */}
        {/* <Footer /> */}
      </>
    );
  }